package com.briup.apps.cms.dao;

import com.briup.apps.cms.bean.RoleAndPrivilege;
import com.briup.apps.cms.bean.RoleAndPrivilegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleAndPrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Thu Nov 14 19:40:36 CST 2019
     */
    long countByExample(RoleAndPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Thu Nov 14 19:40:36 CST 2019
     */
    int deleteByExample(RoleAndPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Thu Nov 14 19:40:36 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Thu Nov 14 19:40:36 CST 2019
     */
    int insert(RoleAndPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Thu Nov 14 19:40:36 CST 2019
     */
    int insertSelective(RoleAndPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Thu Nov 14 19:40:36 CST 2019
     */
    List<RoleAndPrivilege> selectByExample(RoleAndPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Thu Nov 14 19:40:36 CST 2019
     */
    RoleAndPrivilege selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Thu Nov 14 19:40:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") RoleAndPrivilege record, @Param("example") RoleAndPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Thu Nov 14 19:40:36 CST 2019
     */
    int updateByExample(@Param("record") RoleAndPrivilege record, @Param("example") RoleAndPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Thu Nov 14 19:40:36 CST 2019
     */
    int updateByPrimaryKeySelective(RoleAndPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Thu Nov 14 19:40:36 CST 2019
     */
    int updateByPrimaryKey(RoleAndPrivilege record);
}